# Generated by Django 5.0 on 2026-06-02 20:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_searchpreference_operation_type'),
        ('deals', '0002_create_default_stages'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('payment_due_day', models.SmallIntegerField()),
                ('late_fee_percent_daily', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('adjustment_index', models.CharField(choices=[('ICL', 'ICL (BCRA)'), ('IPC', 'IPC (INDEC)'), ('CVS', 'CVS (INDEC)'), ('fixed_percent', 'Porcentaje fijo')], max_length=20)),
                ('adjustment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adjustment_frequency_months', models.SmallIntegerField()),
                ('next_adjustment_date', models.DateField()),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('guarantee_type', models.CharField(choices=[('property_guarantee', 'Garantía propietaria'), ('insurance', 'Seguro de caución'), ('bank_guarantee', 'Aval bancario'), ('direct_debit', 'Débito directo'), ('other', 'Otro')], max_length=30)),
                ('guarantee_detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('expired', 'Vencido'), ('terminated', 'Rescindido')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='deals.deal')),
                ('owner_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_contracts', to='contacts.contact')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='properties.property')),
                ('tenant_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_contracts', to='contacts.contact')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contrato de alquiler',
                'verbose_name_plural': 'contratos de alquiler',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RentAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_date', models.DateField()),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('index_used', models.CharField(choices=[('ICL', 'ICL (BCRA)'), ('IPC', 'IPC (INDEC)'), ('CVS', 'CVS (INDEC)'), ('fixed_percent', 'Porcentaje fijo')], max_length=20)),
                ('index_value_at_date', models.DecimalField(decimal_places=4, max_digits=10)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='contracts.rentalcontract')),
            ],
            options={
                'verbose_name': 'ajuste de alquiler',
                'verbose_name_plural': 'ajustes de alquiler',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adjustment_index', 'fixed_percent'), ('adjustment_percent__isnull', False)), models.Q(('adjustment_index', 'fixed_percent'), _negated=True), _connector='OR'), name='fixed_percent_requires_adjustment_percent'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.CheckConstraint(check=models.Q(('payment_due_day__gte', 1), ('payment_due_day__lte', 28)), name='payment_due_day_valid_range'),
        ),
    ]
