# Generated by Django 5.0 on 2026-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcontract',
            old_name='property_id',
            new_name='property',
        ),
    ]
