# Generated by Django 5.0 on 2026-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_property_id_rentalcontract_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('scheduled', 'Programado'), ('expired', 'Vencido'), ('terminated', 'Rescindido')], default='active', max_length=20),
        ),
    ]
