# Generated by Django 5.0 on 2026-06-02 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_searchpreference_operation_type'),
        ('contracts', '0001_initial'),
        ('deals', '0002_create_default_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('rent_receipt', 'Recibo de alquiler'), ('commission_receipt', 'Recibo de comisión'), ('expense_receipt', 'Recibo de gasto')], max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('concept', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('issued', 'Emitido'), ('cancelled', 'Cancelado')], default='issued', max_length=20)),
                ('pdf_url', models.URLField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='contracts.rentalcontract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='deals.deal')),
                ('payer_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'comprobante',
                'verbose_name_plural': 'comprobantes',
            },
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.CheckConstraint(check=models.Q(('deal__isnull', False), ('contract__isnull', False), _connector='OR'), name='billing_document_requires_deal_or_contract'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'number'), name='unique_number_per_document_type'),
        ),
    ]
