# Generated by Django 5.0 on 2026-07-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingdocument_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdocument',
            name='pdf_url',
        ),
    ]
