# Generated by Django 5.0 on 2026-06-02 19:08

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_type', models.CharField(choices=[('person', 'Persona'), ('company', 'Empresa')], default='person', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('cuil', 'CUIL')], max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Propietario'), ('tenant', 'Inquilino'), ('interested', 'Interesado')], max_length=20)),
                ('source', models.CharField(choices=[('zonaprop', 'Zonaprop'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referido'), ('direct', 'Directo'), ('other', 'Otro')], default='direct', max_length=20)),
                ('source_detail', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(max_length=20)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('area_m2_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bedrooms_min', models.SmallIntegerField(blank=True, null=True)),
                ('neighborhoods', models.JSONField(blank=True, default=list)),
                ('property_types', models.JSONField(blank=True, default=list)),
                ('features_required', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'preferencia de búsqueda',
                'verbose_name_plural': 'preferencias de búsqueda',
            },
        ),
    ]
