# Generated by Django 5.0 on 2026-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpreference',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler'), ('temporary_rent', 'Alquiler temporario')], max_length=20),
        ),
    ]
