# Generated by Django 5.0 on 2026-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_searchpreference_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpreference',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3),
        ),
    ]
