# Generated by Django 5.0 on 2026-07-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_searchpreference_currency'),
        ('properties', '0008_property_parking_spaces_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpreference',
            name='features_required',
        ),
        migrations.AddField(
            model_name='searchpreference',
            name='features_required',
            field=models.ManyToManyField(blank=True, related_name='search_preferences', to='properties.feature'),
        ),
    ]
