# Generated by Django 5.0 on 2026-06-03 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_searchpreference_operation_type'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'evento saliente',
                'verbose_name_plural': 'eventos salientes',
                'indexes': [models.Index(fields=['status'], name='integration_status_a09a97_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('zonaprop', 'Zonaprop'), ('own_website', 'Sitio propio'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='contacts.contact')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='listings.listing')),
            ],
            options={
                'verbose_name': 'evento entrante',
                'verbose_name_plural': 'eventos entrantes',
                'indexes': [models.Index(fields=['status'], name='integration_status_a34f16_idx'), models.Index(fields=['channel'], name='integration_channel_e85853_idx')],
            },
        ),
    ]
