# Generated by Django 5.0 on 2026-06-02 19:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Departamento'), ('house', 'Casa'), ('office', 'Oficina'), ('commercial', 'Local comercial'), ('land', 'Terreno'), ('garage', 'Garage'), ('rural', 'Rural')], max_length=20)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.SmallIntegerField(blank=True, null=True)),
                ('year_built', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('rented', 'Alquilada'), ('sold', 'Vendida'), ('paused', 'Pausada'), ('archived', 'Archivada')], default='available', max_length=20)),
                ('is_external', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('youtube_video_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='contacts.contact')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'propiedad',
                'verbose_name_plural': 'propiedades',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPropertySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('agreed_commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_source', to='properties.property')),
            ],
            options={
                'verbose_name': 'fuente externa',
                'verbose_name_plural': 'fuentes externas',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField()),
                ('mime_type', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
            options={
                'verbose_name': 'archivo multimedia',
                'verbose_name_plural': 'archivos multimedia',
                'ordering': ['order'],
            },
        ),
    ]
