# Generated by Django 5.0 on 2026-06-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalpropertysource',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner_contact_id',
            new_name='owner_contact',
        ),
        migrations.RenameField(
            model_name='propertymedia',
            old_name='property_id',
            new_name='property',
        ),
    ]
