# Generated by Django 5.0 on 2026-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertymedia_file_url_to_r2_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
