# Generated by Django 5.0 on 2026-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
