# Generated by Django 5.0 on 2026-07-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_parking_spaces_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[('general', 'Características generales'), ('caracteristicas', 'Características'), ('servicios', 'Servicios'), ('ambientes', 'Ambientes')], default='caracteristicas', max_length=20),
            preserve_default=False,
        ),
    ]
