# Generated by Django 5.0 on 2026-06-02 19:43

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler'), ('temporary_rent', 'Alquiler temporario')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_min_acceptable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('period', models.CharField(choices=[('total', 'Total'), ('monthly', 'Mensual'), ('daily', 'Diario')], default='total', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de aprobación'), ('published', 'Publicado'), ('paused', 'Pausado'), ('closed', 'Cerrado')], default='draft', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], max_length=3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='listings.listing')),
            ],
            options={
                'verbose_name': 'historial de precio',
                'verbose_name_plural': 'historial de precios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('own_website', 'Sitio propio'), ('zonaprop', 'Zonaprop'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('mercadolibre', 'MercadoLibre')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('failed', 'Fallido'), ('unpublished', 'Despublicado')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='listings.listing')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicación en canal',
                'verbose_name_plural': 'publicaciones en canales',
            },
        ),
        migrations.AddConstraint(
            model_name='listingpublication',
            constraint=models.UniqueConstraint(fields=('listing', 'channel'), name='unique_listing_channel'),
        ),
    ]
