# Generated by Django 5.0 on 2026-06-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='property_id',
            new_name='property',
        ),
    ]
