# Generated by Django 5.0 on 2026-06-09 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_property_id_listing_property'),
        ('properties', '0004_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['published', 'paused'])), fields=('property', 'operation_type'), name='unique_active_listing_per_operation'),
        ),
    ]
