# Generated by Django 5.0 on 2026-07-22 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_unique_active_listing_per_operation'),
        ('properties', '0011_alter_propertymedia_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_active_listing_per_operation',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('deleted_at__isnull', True)), fields=('property', 'operation_type'), name='unique_active_listing_per_operation'),
        ),
    ]
