# Generated by Django 5.0 on 2026-06-02 19:39

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_searchpreference_operation_type'),
        ('listings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_terminal_won', models.BooleanField(default=False)),
                ('is_terminal_lost', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'etapa de pipeline',
                'verbose_name_plural': 'etapas de pipeline',
                'ordering': ['pipeline_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deal_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], max_length=10)),
                ('external_property_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('won', 'Ganado'), ('lost', 'Perdido'), ('cancelled', 'Cancelado')], max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='contacts.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='listings.listing')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.pipelinestage')),
            ],
            options={
                'verbose_name': 'negociación',
                'verbose_name_plural': 'negociaciones',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_history', to='deals.deal')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='deals.pipelinestage')),
            ],
            options={
                'verbose_name': 'historial de etapa',
                'verbose_name_plural': 'historial de etapas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(check=models.Q(('listing__isnull', False), ('external_property_notes__gt', ''), _connector='OR'), name='deal_requires_listing_or_notes'),
        ),
    ]
